export default {
  preset: "ts-jest/presets/default-esm",
  testEnvironment: "node",
  extensionsToTreatAsEsm: [".ts"],
  roots: ["<rootDir>/tests"],
  testMatch: ["**/?(*.)+(spec|test).ts"],
  moduleNameMapper: {
    "^(\\.{1,2}/.*)\\.js$": "$1",
    "^@src/(.*)\\.(js|ts)$": "<rootDir>/src/$1",
    "^@shared/(.*)\\.(js|ts)$": "<rootDir>/../../shared/$1",
    "^@constant/(.*)\\.(js|ts)$": "<rootDir>/../../shared/constant/$1",
    "^@type/(.*)\\.(js|ts)$": "<rootDir>/../../shared/type/$1",
    "^@util/(.*)\\.(js|ts)$": "<rootDir>/../../shared/util/$1",
    "^@config$": "<rootDir>/../../shared/config",
  },
  setupFilesAfterEnv: ["<rootDir>/tests/setupFilesAfterEnv.ts"],
  collectCoverageFrom: ["src/**/*.ts", "!src/**/*.test.ts"],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "html"],
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
  globals: {
    LOG_LEVEL: "error",
  },
};
