export default {
  preset: "ts-jest/presets/default-esm",
  testEnvironment: "node",
  extensionsToTreatAsEsm: [".ts"],
  roots: ["<rootDir>/tests"],
  testMatch: ["**/?(*.)+(spec|test).ts"],
  moduleNameMapper: {
    "^(\\.{1,2}/.*)\\.js$": "$1",
  },
  globalSetup: "<rootDir>/tests/config/globalSetup.ts",
  setupFilesAfterEnv: ["<rootDir>/tests/config/setupFilesAfterEnv.ts"],
  collectCoverageFrom: [
    "circuits/**/*.ts",
    "logic/**/*.ts",
    "util/**/*.ts",
    "!tests/**",
    "!**/*.test.ts",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "html"],
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
  testTimeout: 60000,
  globals: {
    LOG_LEVEL: "error",
    CIRCOM_DEFAULTS: {
      O: 2,
      verbose: false,
      inspect: false,
      json: false,
      recompile: true,
      prime: "bn128",
      simplification_substitution: false,
      no_asm: false,
      no_init: false,
    },
    CONSTRAINT_COUNTS_PATH: "./constraintCounts.json",
  },
};
